name: Test Sphinx site

on:
  pull_request:
    branches: [ 'better-pr-workflow' ]
    paths: [ 'docs/**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Sphinx documentation
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        
    - name: Create new preview branch
      uses: peterjgrainger/action-create-branch@v2.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        branch: ${{ github.head_ref }}-preview
        
    - name: Commit documentation changes to preview branch
      run: |
        git clone https://github.com/pangeo-data/pangeo.git --branch $GITHUB_REF-preview --single-branch gh-pages
        cp -r docs/_build/html/* gh-pages/
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        cd gh-pages
        git add .
        git commit -m "Create preview documentation" -a || true
        
    - name: Push documentation changes to preview branch
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}-preview
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
